name: 'üõ°Ô∏è Verify'

on:
  pull_request:
  push:
    branches:
      - master
      - main

permissions:
  contents: read
  packages: read
  pull-requests: write

jobs:
  git-town:
    runs-on: ubuntu-latest
    steps:
      - uses: git-town/action@v1
        if: github.event_name == 'pull_request'
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/node-install
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          pnpm build
          pnpm lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/node-install
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          pnpm build
          pnpm test
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/node-install
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          pnpm docker:build
